# Generated by Django 3.1.5 on 2021-02-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210211_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='no_of_copies',
            field=models.BigIntegerField(),
        ),
    ]
