# Generated by Django 3.1.5 on 2021-02-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210213_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='no_of_copies',
            field=models.PositiveIntegerField(),
        ),
    ]
