# Generated by Django 3.1.5 on 2021-03-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210308_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='isbn',
            field=models.BigIntegerField(),
        ),
    ]
